# Site settings
title: http/df
email: josiah@collectif.co
description: > # this means to ignore newlines until "baseurl:"
  Free your website from the Internet.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://httpdf.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
exclude: ['/node_modules/','**.sublime-project','**.sublime-workspace','gulpfile.js','package.json','.git']

# Build settings
markdown: kramdown
